{"name": "test_fail1", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail1():\n>       assert False\nE       assert False\n\ntest_fail.py:6: AssertionError"}, "start": 1744878772589, "stop": 1744878772590, "uuid": "3cb9a96c-d713-40a0-8e98-0535031f6091", "historyId": "a68a9f97ebf10f96aa20fbfc83fca78d", "testCaseId": "a68a9f97ebf10f96aa20fbfc83fca78d", "fullName": "test_fail#test_fail1", "labels": [{"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Air-Donchulesko.local"}, {"name": "thread", "value": "56996-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fail"}]}