{"name": "test_fail1", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail1():\n>       assert False\nE       assert False\n\ntests/simple/test_fail.py:6: AssertionError"}, "start": 1744885945289, "stop": 1744885945290, "uuid": "00d19ddf-cd78-49e1-b103-1c753dfba96b", "historyId": "5980a0f138d2262d80936b48f834090e", "testCaseId": "5980a0f138d2262d80936b48f834090e", "fullName": "tests.simple.test_fail#test_fail1", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Air-Donchulesko.local"}, {"name": "thread", "value": "58885-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}